version: '3'

services: 
    db:
        image: postgres:12.0-alpine
        container_name: 'db-postgres'
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=db-book-store
    book-store:
        build: .
        container_name: 'book-store'
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/book-store/
        ports: 
            - "8080:8000"
        env_file:
            - ./.env.dev
        depends_on:
            - db

volumes:
    postgres_data: